_BASE_: hcformer_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2HCResNet"
  RESNETS:
    DEPTH: 50
    AUX: "transformer"
  SEM_SEG_HEAD:
    CONVS_DIM: 256
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "HCStandardTransformerDecoder"
SOLVER:
  STEPS: (655556, 710184)
  MAX_ITER: 737500
